export const BITCOIN_TOPICS = [
  // Genesis & History
  "The Genesis Block and Satoshi Nakamoto's hidden message",
  "Bitcoin Pizza Day and the first real-world transaction",
  "The Silk Road and early adoption history",
  "The Block Size Wars and the scaling debate",
  "The UASF movement and user-activated soft forks",
  "Mt. Gox collapse and lessons learned",
  "The China mining ban and hashrate migration",
  "El Salvador's Bitcoin legal tender experiment",
  "The rise and fall of centralized exchanges",
  "Hal Finney receiving the first Bitcoin transaction",

  // Satoshi & Cypherpunks
  "Cypherpunk history: Tim May, Hal Finney, Nick Szabo",
  "The Satoshi Papers and early writings",
  "Nick Szabo's Bit Gold and smart contracts origins",
  "Wei Dai's b-money proposal",
  "Adam Back and Hashcash origins of proof of work",
  "The cypherpunk mailing list and digital cash dreams",
  "Satoshi's disappearance and decentralized leadership",
  "The Crypto Wars of the 1990s and encryption freedom",

  // Technical Fundamentals
  "The technical mechanics of SHA-256 hashing",
  "Public key cryptography and digital signatures",
  "The Byzantine Generals Problem solution",
  "Unspent Transaction Outputs (UTXO) model",
  "Segregated Witness (SegWit) and transaction malleability",
  "Taproot and Schnorr Signatures",
  "Difficulty adjustment: The heartbeat of the network",
  "The Mempool and fee market dynamics",
  "BIP-324 encrypted P2P transport",
  "Miniscript and advanced spending conditions",
  "Assumeutxo and fast node synchronization",
  "Stratum V2 and decentralized mining pools",
  "Compact block relay and network efficiency",
  "Replace-by-fee (RBF) and transaction replacement",

  // Layer 2 & Scaling
  "The Lightning Network and Layer 2 solutions",
  "Lightning channel management and liquidity",
  "Submarine swaps and atomic swaps",
  "Fedimint and federated ecash",
  "Cashu and the ecash renaissance",
  "Lightning Service Providers (LSPs)",
  "Channel factories and scaling solutions",
  "BOLT specifications and Lightning interoperability",
  "Splicing and dynamic channel management",

  // Economics & Austrian Theory
  "Austrian Economics and the theory of sound money",
  "The 21 million hard cap and scarcity",
  "The Halving cycles and stock-to-flow models",
  "The Cantillon Effect and fiat wealth transfer",
  "Time preference and civilization building",
  "Gresham's Law: Bad money drives out good",
  "Sound money vs fiat money throughout history",
  "The petrodollar system and its fragility",
  "Monetary debasement from Rome to today",
  "Seigniorage and hidden taxation",
  "The gold standard era and its collapse",
  "Hyperinflation case studies: Zimbabwe, Venezuela, Weimar",
  "Bitcoin as a savings technology",
  "The separation of Money and State",
  "Digital gold vs digital cash narrative evolution",

  // Security & Self-Custody
  "Cold storage, hardware wallets, and air-gapped security",
  "Multisig vaults and collaborative custody",
  "Running a full node and personal independence",
  "The philosophy of 'Don't Trust, Verify'",
  "Seed phrase security and backup strategies",
  "Passphrases and decoy wallets",
  "Shamir's Secret Sharing for key backup",
  "Hardware wallet supply chain security",
  "Social recovery and inheritance planning",
  "Covenants and spending restrictions",

  // Privacy
  "Privacy technologies: CoinJoin and Coin Control",
  "PayJoin and steganographic transactions",
  "Silent Payments and reusable addresses",
  "Tor, VPNs, and network-level privacy",
  "Chain analysis companies and surveillance capitalism",
  "UTXO management for privacy",
  "The fungibility problem and tainted coins",
  "Privacy as a human right",

  // Energy & Mining (Daniel Batten)
  "The energy consumption debate and Proof of Work thermodynamics",
  "Miners as energy buyers of last resort",
  "Bitcoin mining and methane mitigation",
  "Stranded energy monetization through mining",
  "ESG narratives debunked: Bitcoin's environmental case",
  "Mining and electrical grid stabilization",
  "Renewable energy and mining synergies",
  "Flare gas capture and Bitcoin mining",
  "Mining as demand response for grids",
  "The Cambridge Bitcoin Electricity Index explained",
  "Energy density and proof of work efficiency",
  "Mining difficulty and energy security",
  "Heat recycling from Bitcoin mining operations",
  "Volcano mining in El Salvador",
  "Ocean thermal energy and Bitcoin mining",

  // Human Rights & Global South (Alex Gladstein)
  "Censorship resistance and human rights",
  "Bitcoin as a tool for financial sovereignty in authoritarian regimes",
  "Bitcoin adoption in Nigeria and the eNaira resistance",
  "Venezuela: Bitcoin as an escape from bolivar hyperinflation",
  "Cuba and financial censorship circumvention",
  "Bitcoin for dissidents and journalists under repression",
  "The Human Rights Foundation and Bitcoin development grants",
  "Financial inclusion in the Global South",
  "Remittances and Bitcoin's cost savings",
  "Women's financial empowerment through Bitcoin",
  "LGBTQ+ financial freedom in hostile jurisdictions",
  "Protest movements and financial deplatforming",
  "The Canadian trucker convoy and frozen bank accounts",
  "CBDCs vs Bitcoin: Surveillance money vs freedom money",
  "Bitcoin in refugee communities",
  "Dollarization vs Bitcoinization",
  "Myanmar resistance and Bitcoin donations",
  "Belarus opposition funding through Bitcoin",
  "Ukraine war donations in Bitcoin",
  "Bitcoin as peaceful protest",

  // Policy & Regulation (Bitcoin Policy Institute)
  "Legal tender laws and Bitcoin adoption",
  "Bitcoin regulatory frameworks around the world",
  "Tax treatment of Bitcoin: Property vs currency",
  "Self-custody rights and regulatory threats",
  "Financial privacy laws and Bitcoin",
  "Mining policy and energy regulation",
  "Bitcoin and securities law debates",
  "State-level Bitcoin legislation in the US",
  "The EU's MiCA regulations",
  "Operation Choke Point 2.0 and banking discrimination",
  "The right to transact and financial freedom",
  "KYC/AML overreach and privacy erosion",
  "Central bank policy and Bitcoin's monetary competition",
  "Bitcoin ETFs and institutional adoption",
  "Strategic Bitcoin reserves debate",

  // Books & Essential Reading
  "The Bitcoin Standard by Saifedean Ammous",
  "The Fiat Standard: The debt slavery alternative to human civilization",
  "Broken Money by Lyn Alden: A monetary history",
  "The Blocksize War by Jonathan Bier",
  "Inventing Bitcoin by Yan Pritzker",
  "21 Lessons by Gigi: What I've learned from falling down the Bitcoin rabbit hole",
  "The Sovereign Individual: Prophecy of Bitcoin",
  "The Price of Tomorrow by Jeff Booth: Deflation and abundance",
  "Thank God for Bitcoin: The creation, corruption and redemption of money",
  "Mastering Bitcoin by Andreas Antonopoulos",
  "The Little Bitcoin Book: Why Bitcoin matters for your freedom",
  "Gradually Then Suddenly by Parker Lewis",
  "Layered Money by Nik Bhatia",
  "The Internet of Money series by Andreas Antonopoulos",
  "Softwar by Jason Lowery: Thesis on proof of work as national defense",
  "Bitcoin Clarity by Kiara Bickers",
  "Bitcoin: Hard Money You Can't F*ck With by Jason Williams",
  "The Book of Satoshi compiled by Phil Champagne",
  "Bitcoin Billionaires by Ben Mezrich",
  "Digital Gold by Nathaniel Popper",

  // Culture & Philosophy
  "Toxic maximalism: Conviction or tribalism?",
  "Low time preference as a lifestyle philosophy",
  "The citadel meme and future speculation",
  "HODL culture and its origins from bitcointalk",
  "Number go up technology and adoption curves",
  "Stacking sats: Dollar cost averaging philosophy",
  "Not your keys, not your coins: The mantra explained",
  "Timechain vs Blockchain terminology",
  "The distinction between Bitcoin and 'Crypto'",
  "Bitcoin as a religion: Faith, conviction, and community",
  "The orange pill metaphor and awakening",
  "Proof of work as unforgeable costliness",
  "Bitcoin's immaculate conception: No premine, no founder reward",
  "The honey badger meme: Bitcoin doesn't care",
  "Fix the money, fix the world philosophy",
  "Hyperbitcoinization scenarios",
  "Bitcoin circular economies",
  "Generational wealth and Bitcoin inheritance",

  // Technical Debates & Developments
  "Ordinals and inscriptions: Innovation or spam?",
  "RGB protocol and client-side validation",
  "Ark protocol and virtual UTXOs",
  "Drivechains and BIP-300 debate",
  "OP_CAT reactivation proposals",
  "BitVM and Bitcoin smart contracts",
  "Statechains and off-chain ownership transfer",
  "BIPs (Bitcoin Improvement Proposals) governance process",
  "Soft forks vs hard forks: Bitcoin's upgrade philosophy",
  "Core development and decentralized contribution",

  // Nostr & Adjacent Tech
  "Nostr: Notes and Other Stuff Transmitted by Relays",
  "Zaps: Lightning payments on social media",
  "Value 4 Value model and content monetization",
  "Decentralized identity on Nostr",
  "Bitcoin and censorship-resistant publishing",
];
