export const BITCOIN_TOPICS = [
  "The Genesis Block and Satoshi Nakamoto's hidden message",
  "The technical mechanics of SHA-256 hashing",
  "Austrian Economics and the theory of sound money",
  "The 21 million hard cap and scarcity",
  "The philosophy of 'Don't Trust, Verify'",
  "Public key cryptography and digital signatures",
  "The Byzantine Generals Problem solution",
  "The Block Size Wars and the scaling debate",
  "Segregated Witness (SegWit) and transaction malleability",
  "The Lightning Network and Layer 2 solutions",
  "Taproot and Schnorr Signatures",
  "The energy consumption debate and Proof of Work thermodynamics",
  "Censorship resistance and human rights",
  "Bitcoin as a tool for financial sovereignty in authoritarian regimes",
  "The Halving cycles and stock-to-flow models",
  "Cold storage, hardware wallets, and air-gapped security",
  "Multisig vaults and collaborative custody",
  "Running a full node and personal independence",
  "The Mempool and fee market dynamics",
  "Difficulty adjustment: The heartbeat of the network",
  "Cypherpunk history: Tim May, Hal Finney, Nick Szabo",
  "Bitcoin Pizza Day and the first real-world transaction",
  "Hyperbitcoinization scenarios",
  "Privacy technologies: CoinJoin and Coin Control",
  "Miners as energy buyers of last resort",
  "The distinction between Bitcoin and 'Crypto'",
  "Timechain vs Blockchain terminology",
  "Unspent Transaction Outputs (UTXO) model",
  "BIPs (Bitcoin Improvement Proposals) governance process",
  "The Silk Road and early adoption history",
  "Separation of Money and State",
  "Digital gold vs Digital cash narrative evolution"
];